name: Git Clone
description: Simple git clone of an extra repository
author: https://github.com/first-aml/
requirements: []
configuration:
  properties:
    repository:
      type: string
  additionalProperties: false